server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: links-service
          uri: lb://links-service
          predicates:
            - Path=/links/**
        - id: categories-service
          uri: lb://categories-service
          predicates:
            - Path=/categories/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka