server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: links-service
          uri: lb://links-service
          predicates:
            - Path=/api/links/**
        - id: categories-service
          uri: lb://categories-service
          predicates:
            - Path=/api/categories/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka